species:
  - name: Species1
    speed: 6
    energy_decay: 0.995
    max_age: 30
    min_reproduction_age: 5
    max_reproduction_age: 25
    reproduction_probability: 0.5
    reproduction_energy_threshold: 40
    gestation_period: 1
    birth_energy_cost: 20
    litter_size: 2
    mating_weight: 1.0
    predators:
      - Species2
    diet:
      Species2:
        energy: 20
        eating_probability: 0.9
        type: 'animal'
    pack_size: 10
    color: "#FF0000"
    hunger_energy_penalty: 5.0
    death_probability: 0.02  
    food_weight: 1.0         
    food_weight_multiplier: 2.0

  - name: Species2
    speed: 6
    energy_decay: 0.995
    max_age: 30
    min_reproduction_age: 5
    max_reproduction_age: 25
    reproduction_probability: 0.5
    reproduction_energy_threshold: 40
    gestation_period: 1
    birth_energy_cost: 20
    litter_size: 2
    mating_weight: 1.0
    predators:
      - Species3
    diet:
      Species3:
        energy: 20
        eating_probability: 0.9
        type: 'animal'
    pack_size: 10
    color: "#00FF00"
    hunger_energy_penalty: 5.0
    death_probability: 0.02  
    food_weight: 1.0         
    food_weight_multiplier: 2.0

  - name: Species3
    speed: 6
    energy_decay: 0.995
    max_age: 30
    min_reproduction_age: 5
    max_reproduction_age: 25
    reproduction_probability: 0.5
    reproduction_energy_threshold: 40
    gestation_period: 1
    birth_energy_cost: 20
    litter_size: 2
    mating_weight: 1.0
    predators:
      - Species1
    diet:
      Species1:
        energy: 20
        eating_probability: 0.9
        type: 'animal'
    pack_size: 10
    color: "#0000FF"
    hunger_energy_penalty: 5.0
    death_probability: 0.02  
    food_weight: 1.0         
    food_weight_multiplier: 2.0  

simulation:
  map_size:
    width: 100
    height: 100
  ages: 10
  initial_population:
    Species1: 15
    Species2: 15
    Species3: 15
