species:
  - name: 'Species A'
    initial_population: 50
    birth_rate: 0.1
    death_rate: 0.05
    carrying_capacity: 1000  
    color: 'green'
  - name: 'Species B'
    initial_population: 30
    birth_rate: 0.1
    death_rate: 0.05
    carrying_capacity: 1000  
    color: 'red'
  - name: 'Species C'
    initial_population: 20
    birth_rate: 0.1
    death_rate: 0.05
    carrying_capacity: 1000  
    color: 'blue'

interaction_matrix:
  - [0.0, -0.5, 0.5]  
  - [0.5, 0.0, -0.5]  
  - [-0.5, 0.5, 0.0]   